"""initial schema

Revision ID: db7ac78ea1ee
Revises: 
Create Date: 2026-08-14 10:10:59.732621
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db7ac78ea1ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('reputation_score >= 0 AND reputation_score <= 1', name='ck_brand_reputation'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_slug'), ['slug'], unique=True)

    op.create_table('categories',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('model_predictions',
    sa.Column('model_name', sa.String(length=60), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('prediction', sa.Float(), nullable=False),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_predictions_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_model_version'), ['model_version'], unique=False)
        batch_op.create_index('ix_model_predictions_name_time', ['model_name', 'predicted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_predicted_at'), ['predicted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_succeeded'), ['succeeded'], unique=False)

    op.create_table('model_registry',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('algorithm', sa.String(length=80), nullable=False),
    sa.Column('artifact_path', sa.String(length=512), nullable=False),
    sa.Column('dataset_version', sa.String(length=40), nullable=False),
    sa.Column('training_rows', sa.Integer(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_duration_s', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('baseline_stats', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("stage IN ('development','staging','production','archived')", name='ck_model_stage'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_name_version')
    )
    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_registry_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_registry_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_registry_name'), ['name'], unique=False)
        batch_op.create_index('ix_model_registry_name_active', ['name', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_registry_stage'), ['stage'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('signup_source', sa.String(length=40), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_categories', sa.JSON(), nullable=False),
    sa.Column('preferred_brands', sa.JSON(), nullable=False),
    sa.Column('price_sensitivity', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('user','admin','analyst')", name='ck_user_role'),
    sa.CheckConstraint('price_sensitivity >= 0 AND price_sensitivity <= 1', name='ck_user_price_sensitivity'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_last_active_at'), ['last_active_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('customer_segments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('segment_label', sa.String(length=40), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('recency_days', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Float(), nullable=False),
    sa.Column('monetary', sa.Float(), nullable=False),
    sa.Column('avg_order_value', sa.Float(), nullable=False),
    sa.Column('product_diversity', sa.Float(), nullable=False),
    sa.Column('session_frequency', sa.Float(), nullable=False),
    sa.Column('rfm_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_segments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_segments_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_segments_segment_label'), ['segment_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_segments_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_segment_label_version', ['segment_label', 'model_version'], unique=False)
        batch_op.create_index('ix_segment_user_version', ['user_id', 'model_version'], unique=True)

    op.create_table('orders',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending','paid','shipped','delivered','cancelled','returned')", name='ck_order_status'),
    sa.CheckConstraint('total_amount >= 0', name='ck_order_total_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_placed_at'), ['placed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_orders_user_placed', ['user_id', 'placed_at'], unique=False)

    op.create_table('products',
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('base_cost', sa.Float(), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rating_avg', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('inventory', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('specifications', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('launched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('discount_pct >= 0 AND discount_pct < 100', name='ck_product_discount_range'),
    sa.CheckConstraint('inventory >= 0', name='ck_product_inventory_non_negative'),
    sa.CheckConstraint('price >= 0', name='ck_product_price_non_negative'),
    sa.CheckConstraint('rating_avg >= 0 AND rating_avg <= 5', name='ck_product_rating_range'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index('ix_products_category_active', ['category_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_inventory'), ['inventory'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_products_price_rating', ['price', 'rating_avg'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_rating_avg'), ['rating_avg'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_title'), ['title'], unique=False)

    op.create_table('user_features',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=64), nullable=False),
    sa.Column('feature_value', sa.Float(), nullable=False),
    sa.Column('feature_version', sa.String(length=40), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'feature_name', 'feature_version', name='uq_user_feature')
    )
    with op.batch_alter_table('user_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_features_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_features_feature_name'), ['feature_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_features_feature_version'), ['feature_version'], unique=False)
        batch_op.create_index('ix_user_features_name_version', ['feature_name', 'feature_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_features_user_id'), ['user_id'], unique=False)

    op.create_table('forecasts',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_demand', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('actual_demand', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('horizon_days > 0', name='ck_forecast_horizon_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'target_date', 'model_version', name='uq_forecast_product_date')
    )
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecasts_horizon_days'), ['horizon_days'], unique=False)
        batch_op.create_index('ix_forecasts_product_horizon', ['product_id', 'horizon_days'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_target_date'), ['target_date'], unique=False)

    op.create_table('order_items',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_item_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_order_item_price_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index('ix_order_items_product_order', ['product_id', 'order_id'], unique=False)

    op.create_table('price_predictions',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('predicted_price', sa.Float(), nullable=False),
    sa.Column('expected_demand', sa.Float(), nullable=False),
    sa.Column('price_trend', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('feature_contributions', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint("price_trend IN ('up','down','stable')", name='ck_price_trend'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_price_confidence'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_predictions_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_predictions_price_trend'), ['price_trend'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_predictions_product_id'), ['product_id'], unique=False)
        batch_op.create_index('ix_price_predictions_product_time', ['product_id', 'generated_at'], unique=False)

    op.create_table('product_features',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=64), nullable=False),
    sa.Column('feature_value', sa.Float(), nullable=False),
    sa.Column('feature_version', sa.String(length=40), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'feature_name', 'feature_version', name='uq_product_feature')
    )
    with op.batch_alter_table('product_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_features_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_features_feature_name'), ['feature_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_features_feature_version'), ['feature_version'], unique=False)
        batch_op.create_index('ix_product_features_name_version', ['feature_name', 'feature_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_features_product_id'), ['product_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('surface', sa.String(length=40), nullable=False),
    sa.Column('strategy', sa.String(length=40), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('clicked', sa.Boolean(), nullable=False),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.Column('served_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_clicked'), ['clicked'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_converted'), ['converted'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_served_at'), ['served_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_strategy'), ['strategy'], unique=False)
        batch_op.create_index('ix_recommendations_strategy_time', ['strategy', 'served_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_surface'), ['surface'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_recommendations_user_surface', ['user_id', 'surface'], unique=False)

    op.create_table('reviews',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('verified_purchase', sa.Boolean(), nullable=False),
    sa.Column('helpful_votes', sa.Integer(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=10), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_model_version', sa.String(length=40), nullable=True),
    sa.Column('aspects', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("sentiment_label IS NULL OR sentiment_label IN ('positive','neutral','negative')", name='ck_review_sentiment_label'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_product_id'), ['product_id'], unique=False)
        batch_op.create_index('ix_reviews_product_rating', ['product_id', 'rating'], unique=False)
        batch_op.create_index('ix_reviews_product_user', ['product_id', 'user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_reviews_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_sentiment_label'), ['sentiment_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('search_events',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('normalized_query', sa.String(length=255), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('clicked_product_id', sa.Integer(), nullable=True),
    sa.Column('clicked_position', sa.Integer(), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['clicked_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_events_normalized_query'), ['normalized_query'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_events_query'), ['query'], unique=False)
        batch_op.create_index('ix_search_events_query_time', ['normalized_query', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_events_user_id'), ['user_id'], unique=False)

    op.create_table('user_events',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint("event_type IN ('product_view','search','click','add_to_cart','remove_from_cart','wishlist','purchase','review')", name='ck_user_event_type'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_events_product_id'), ['product_id'], unique=False)
        batch_op.create_index('ix_user_events_product_type', ['product_id', 'event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_user_events_type_time', ['event_type', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_events_user_time', ['user_id', 'occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_events', schema=None) as batch_op:
        batch_op.drop_index('ix_user_events_user_time')
        batch_op.drop_index(batch_op.f('ix_user_events_user_id'))
        batch_op.drop_index('ix_user_events_type_time')
        batch_op.drop_index(batch_op.f('ix_user_events_session_id'))
        batch_op.drop_index('ix_user_events_product_type')
        batch_op.drop_index(batch_op.f('ix_user_events_product_id'))
        batch_op.drop_index(batch_op.f('ix_user_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_user_events_event_type'))

    op.drop_table('user_events')
    with op.batch_alter_table('search_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_search_events_session_id'))
        batch_op.drop_index('ix_search_events_query_time')
        batch_op.drop_index(batch_op.f('ix_search_events_query'))
        batch_op.drop_index(batch_op.f('ix_search_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_search_events_normalized_query'))

    op.drop_table('search_events')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_sentiment_label'))
        batch_op.drop_index(batch_op.f('ix_reviews_rating'))
        batch_op.drop_index('ix_reviews_product_user')
        batch_op.drop_index('ix_reviews_product_rating')
        batch_op.drop_index(batch_op.f('ix_reviews_product_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_created_at'))

    op.drop_table('reviews')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index('ix_recommendations_user_surface')
        batch_op.drop_index(batch_op.f('ix_recommendations_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_surface'))
        batch_op.drop_index('ix_recommendations_strategy_time')
        batch_op.drop_index(batch_op.f('ix_recommendations_strategy'))
        batch_op.drop_index(batch_op.f('ix_recommendations_served_at'))
        batch_op.drop_index(batch_op.f('ix_recommendations_product_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_converted'))
        batch_op.drop_index(batch_op.f('ix_recommendations_clicked'))

    op.drop_table('recommendations')
    with op.batch_alter_table('product_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_features_product_id'))
        batch_op.drop_index('ix_product_features_name_version')
        batch_op.drop_index(batch_op.f('ix_product_features_feature_version'))
        batch_op.drop_index(batch_op.f('ix_product_features_feature_name'))
        batch_op.drop_index(batch_op.f('ix_product_features_computed_at'))

    op.drop_table('product_features')
    with op.batch_alter_table('price_predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_price_predictions_product_time')
        batch_op.drop_index(batch_op.f('ix_price_predictions_product_id'))
        batch_op.drop_index(batch_op.f('ix_price_predictions_price_trend'))
        batch_op.drop_index(batch_op.f('ix_price_predictions_generated_at'))

    op.drop_table('price_predictions')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index('ix_order_items_product_order')
        batch_op.drop_index(batch_op.f('ix_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_created_at'))

    op.drop_table('order_items')
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecasts_target_date'))
        batch_op.drop_index(batch_op.f('ix_forecasts_product_id'))
        batch_op.drop_index('ix_forecasts_product_horizon')
        batch_op.drop_index(batch_op.f('ix_forecasts_horizon_days'))

    op.drop_table('forecasts')
    with op.batch_alter_table('user_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_features_user_id'))
        batch_op.drop_index('ix_user_features_name_version')
        batch_op.drop_index(batch_op.f('ix_user_features_feature_version'))
        batch_op.drop_index(batch_op.f('ix_user_features_feature_name'))
        batch_op.drop_index(batch_op.f('ix_user_features_computed_at'))

    op.drop_table('user_features')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_title'))
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_rating_avg'))
        batch_op.drop_index('ix_products_price_rating')
        batch_op.drop_index(batch_op.f('ix_products_is_active'))
        batch_op.drop_index(batch_op.f('ix_products_inventory'))
        batch_op.drop_index(batch_op.f('ix_products_created_at'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.drop_index('ix_products_category_active')
        batch_op.drop_index(batch_op.f('ix_products_brand_id'))

    op.drop_table('products')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_user_placed')
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_placed_at'))
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))

    op.drop_table('orders')
    with op.batch_alter_table('customer_segments', schema=None) as batch_op:
        batch_op.drop_index('ix_segment_user_version')
        batch_op.drop_index('ix_segment_label_version')
        batch_op.drop_index(batch_op.f('ix_customer_segments_user_id'))
        batch_op.drop_index(batch_op.f('ix_customer_segments_segment_label'))
        batch_op.drop_index(batch_op.f('ix_customer_segments_model_version'))
        batch_op.drop_index(batch_op.f('ix_customer_segments_created_at'))

    op.drop_table('customer_segments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_last_active_at'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_registry_stage'))
        batch_op.drop_index('ix_model_registry_name_active')
        batch_op.drop_index(batch_op.f('ix_model_registry_name'))
        batch_op.drop_index(batch_op.f('ix_model_registry_is_active'))
        batch_op.drop_index(batch_op.f('ix_model_registry_created_at'))

    op.drop_table('model_registry')
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_predictions_succeeded'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_predicted_at'))
        batch_op.drop_index('ix_model_predictions_name_time')
        batch_op.drop_index(batch_op.f('ix_model_predictions_model_version'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_model_name'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_entity_id'))

    op.drop_table('model_predictions')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))
        batch_op.drop_index(batch_op.f('ix_categories_created_at'))

    op.drop_table('categories')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_slug'))
        batch_op.drop_index(batch_op.f('ix_brands_created_at'))

    op.drop_table('brands')
    # ### end Alembic commands ###
