"""E-Commerce Intelligence API.

FastAPI application factory: wires configuration, middleware, exception handling,
routing and the ML warm-up/shutdown lifecycle.
"""
from __future__ import annotations

import sys
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

# The `ml` package lives at the repository root, one level above `backend/`.
REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from fastapi import FastAPI  # noqa: E402
from fastapi.middleware.cors import CORSMiddleware  # noqa: E402
from fastapi.middleware.gzip import GZipMiddleware  # noqa: E402
from fastapi.responses import RedirectResponse  # noqa: E402

from app.api.v1 import api_router  # noqa: E402
from app.core.cache import get_cache  # noqa: E402
from app.core.config import settings  # noqa: E402
from app.core.db import create_all, ping  # noqa: E402
from app.core.errors import register_exception_handlers  # noqa: E402
from app.core.logging_config import configure_logging, get_logger  # noqa: E402
from app.middleware import RateLimitMiddleware, RequestContextMiddleware, SecurityHeadersMiddleware  # noqa: E402
from app.ml.model_store import get_model_store  # noqa: E402

configure_logging(settings.LOG_LEVEL, json_output=settings.LOG_JSON)
logger = get_logger("main")

DESCRIPTION = """
AI-powered e-commerce intelligence platform.

**Capabilities**

* Hybrid product search - BM25 keyword matching + dense-vector semantic retrieval,
  typo tolerance, natural-language constraint parsing, configurable ranking.
* Hybrid recommendations - latent-factor and item-item collaborative filtering,
  content similarity, popularity, personalization and business signals, with
  cold-start routing and per-item explanations.
* Demand forecasting - weekly seasonal-naive baseline corrected by a gradient
  boosted residual model, exposed at 7/14/30-day horizons with prediction intervals.
* Price intelligence - model-implied pricing with global and per-product explainability.
* Review sentiment - three-class classification plus aspect-level polarity extraction.
* Customer segmentation - RFM + K-Means with business-readable segment names.
* Full MLOps surface - model registry, drift detection, latency and error-rate monitoring.

**Authentication** - Admin analytics and ML monitoring endpoints require a bearer
token with the `admin` role. Obtain one from `POST /api/v1/auth/login`.

All catalogue, customer and transaction data shipped with this project is
**synthetic** and generated by `ml/datasets/synthetic.py`.
"""

TAGS_METADATA = [
    {"name": "health", "description": "Liveness, readiness and dependency health probes."},
    {"name": "auth", "description": "JWT issuance and identity."},
    {"name": "products", "description": "Catalogue browse, product detail, reviews and related items."},
    {"name": "search", "description": "Hybrid search, autocomplete and query analytics."},
    {"name": "recommendations", "description": "Personalized recommendation surfaces."},
    {"name": "events", "description": "Behavioural event ingestion - the ML training signal."},
    {"name": "users", "description": "User records, preference profiles and order history."},
    {"name": "intelligence", "description": "Sentiment, forecasting, pricing and segmentation."},
    {"name": "analytics", "description": "Business and AI analytics (admin only)."},
    {"name": "ml-monitoring", "description": "Model registry, drift and serving health (admin only)."},
]


@asynccontextmanager
async def lifespan(app: FastAPI):
    problems = settings.validate_production()
    for problem in problems:
        logger.error("production_config_problem", problem=problem)
    if problems and settings.is_production:
        raise RuntimeError("Refusing to start in production with insecure configuration: "
                           + "; ".join(problems))

    if settings.is_sqlite:
        # SQLite is the zero-setup path; PostgreSQL schema is owned by Alembic.
        create_all()

    db_ok = ping()
    cache = get_cache()
    logger.info("startup", environment=settings.ENVIRONMENT, database_ok=db_ok,
                cache_backend=cache.backend_name, sqlite=settings.is_sqlite)

    if settings.ML_AUTOLOAD:
        warmed = get_model_store().warm_up()
        logger.info("models_warmed", **warmed)

    yield

    flushed = get_model_store().flush_predictions()
    logger.info("shutdown", flushed_prediction_logs=flushed)


def create_app() -> FastAPI:
    app = FastAPI(
        title=settings.APP_NAME,
        description=DESCRIPTION,
        version="1.0.0",
        openapi_tags=TAGS_METADATA,
        lifespan=lifespan,
        docs_url="/docs",
        redoc_url="/redoc",
        openapi_url="/openapi.json",
        contact={"name": "E-Commerce Intelligence"},
        license_info={"name": "MIT"},
    )

    # Order matters: the outermost middleware runs first on the way in.
    app.add_middleware(SecurityHeadersMiddleware)
    app.add_middleware(RequestContextMiddleware)
    app.add_middleware(RateLimitMiddleware)
    app.add_middleware(GZipMiddleware, minimum_size=1000)
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins or ["http://localhost:3000"],
        allow_credentials=True,
        allow_methods=["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
        allow_headers=["*"],
        expose_headers=["X-Request-Id", "X-Response-Time-Ms", "X-RateLimit-Remaining"],
    )

    register_exception_handlers(app)
    app.include_router(api_router, prefix=settings.API_V1_PREFIX)

    @app.get("/", include_in_schema=False)
    def root() -> RedirectResponse:
        return RedirectResponse(url="/docs")

    @app.get("/api", include_in_schema=False)
    def api_info() -> dict[str, Any]:
        return {
            "name": settings.APP_NAME,
            "version": "1.0.0",
            "environment": settings.ENVIRONMENT,
            "api_prefix": settings.API_V1_PREFIX,
            "documentation": {"swagger": "/docs", "redoc": "/redoc", "openapi": "/openapi.json"},
            "data_notice": "All bundled catalogue and customer data is synthetic.",
        }

    return app


app = create_app()
